name: Java CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
          java-package: jdk+fx

      - name: Compile
        run: javac src/*.java -d build/classes

      - name: Create JAR
        run: $JAVA_HOME/bin/javapackager -createjar -appclass Menu -srcdir build/classes -outdir build -outfile SpaceGame -v

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: SpaceGame.jar
          path: build/SpaceGame.jar

  create-package-windows:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
          java-package: jdk+fx

      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: SpaceGame.jar

      - name: Create self-contained Windows package
        run: |
          New-Item -ItemType Directory build -Force
          & "${env:JAVA_HOME}\bin\javapackager.exe" -deploy -appclass Menu -name SpaceGame -native image -outdir build -outfile SpaceGame -title SpaceGame -srcdir . -srcfiles SpaceGame.jar -v
          Compress-Archive -Path build\bundles\SpaceGame\* -DestinationPath SpaceGame.zip -Force

      - name: Upload Windows packages
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: SpaceGame.zip

  create-package-linux:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8
          java-package: jdk+fx

      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: SpaceGame.jar

      - name: Create self-contained Linux package
        run: |
          mkdir -p build
          $JAVA_HOME/bin/javapackager -deploy -appclass Menu -name SpaceGame -native image -outdir build -outfile SpaceGame -title SpaceGame -srcdir . -srcfiles SpaceGame.jar -v
          tar --directory build/bundles/SpaceGame --create --file SpaceGame.tar .
          gzip --best --keep SpaceGame.tar
          xz -9 --keep SpaceGame.tar

      - name: Upload Linux packages
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: SpaceGame.tar.*

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - create-package-linux
      - create-package-windows
    steps:
      - uses: actions/download-artifact@v2
        id: download
      - name: Display structure of downloaded files
        run: ls -R
      - name: Rename files
        run: |
          mv ${{steps.download.outputs.download-path}}/linux/SpaceGame.tar.gz ./SpaceGame_linux.tar.gz
          mv ${{steps.download.outputs.download-path}}/linux/SpaceGame.tar.xz ./SpaceGame_linux.tar.xz
          mv ${{steps.download.outputs.download-path}}/windows/SpaceGame.zip ./SpaceGame_windows.zip
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: >-
            ${{steps.download.outputs.download-path}}/SpaceGame.jar/SpaceGame.jar,
            SpaceGame_linux.tar.gz,
            SpaceGame_linux.tar.xz,
            SpaceGame_windows.zip
          omitBody: true
          token: ${{ secrets.GITHUB_TOKEN }}